Traceback (most recent call last):
  File "C:\Users\Egi Putra Ragil\AppData\Roaming\Python\Python310\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Egi Putra Ragil\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Egi Putra Ragil\AppData\Roaming\Python\Python310\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Egi Putra Ragil\AppData\Roaming\Python\Python310\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Egi Putra Ragil\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Egi Putra Ragil\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Egi Putra Ragil\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Egi Putra Ragil\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
(count_doc_lda, count_topic_lda) = lda_top.shape
print(f"Jumlah dokumen\t: {count_doc_lda}")
print(f"Jumlah topik\t: {count_word_lda}")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [28][0m, in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      1[0m (count_doc_lda, count_topic_lda) [38;5;241m=[39m lda_top[38;5;241m.[39mshape
[0;32m      2[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mJumlah dokumen[39m[38;5;130;01m\t[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00mcount_doc_lda[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m----> 3[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mJumlah topik[39m[38;5;130;01m\t[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00mcount_word_lda[38;5;132;01m}[39;00m[38;5;124m"[39m)

[1;31mNameError[0m: name 'count_word_lda' is not defined
NameError: name 'count_word_lda' is not defined

